# Feature Engineering on the cleaned Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
df=pd.read_csv('Output/df_india_cleaned', encoding='latin-1')
df.head()

,Restaurant ID,Restaurant Name,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,...,Has Online delivery,Price range,Aggregate rating,Rating color,Rating text,Votes,n_outlets,Is Chain,Is Rated,Is NCR
0,3400025,Jahanpanah,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",78.011544,27.161661,"North Indian, Mughlai",850,...,No,3,3.9,Yellow,Good,140,1,False,True,False
1,3400341,Rangrezz Restaurant,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",0.000000,0.000000,"North Indian, Mughlai",700,...,No,2,3.5,Yellow,Good,71,1,False,True,False
2,3400005,Time2Eat - Mama Chicken,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,North Indian,500,...,No,2,3.6,Yellow,Good,94,1,False,True,False
3,3400021,Chokho Jeeman Marwari Jain Bhojanalya,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,"Civil Lines, Agra",77.998092,27.195928,Rajasthani,400,...,No,2,4.0,Green,Very Good,87,1,False,True,False
4,3400017,Pinch Of Spice,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,"Civil Lines, Agra",78.007553,27.201725,"North Indian, Chinese, Mughlai",1000,...,No,3,4.2,Green,Very Good,177,1,False,True,False

### Per-restaurant cuisines:
This are the number of cuisines that the restaurants servers.
### Primary cuisines:
This are the restaurant's main cuisine, zomato lists the dominant cuisines first.

In [3]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Has Table booking', 'Has Online delivery',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'n_outlets', 'Is Chain', 'Is Rated', 'Is NCR'],
      dtype='object')

In [4]:
df['Cuisines']

0                                   North Indian, Mughlai
1                                   North Indian, Mughlai
2                                            North Indian
3                                              Rajasthani
4                          North Indian, Chinese, Mughlai
                              ...
8638    Continental, Seafood, Chinese, North Indian, B...
8639                          Cafe, North Indian, Chinese
8640                               Burger, Pizza, Biryani
8641            American, North Indian, Thai, Continental
8642                                              Italian
Name: Cuisines, Length: 8643, dtype: object

In [5]:
cuisines_split=df['Cuisines'].str.split(',')
df['Cuisines Count']=cuisines_split.apply(len)
df['Primary Cuisine']=cuisines_split.apply(lambda x: x[0])

In [6]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Has Table booking', 'Has Online delivery',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'n_outlets', 'Is Chain', 'Is Rated', 'Is NCR',
       'Cuisines Count', 'Primary Cuisine'],
      dtype='object')

In [7]:
df[['Restaurant Name', 'Cuisines Count', 'Primary Cuisine']]

                            Restaurant Name  Cuisines Count Primary Cuisine
0                                Jahanpanah               2    North Indian
1                       Rangrezz Restaurant               2    North Indian
2                   Time2Eat - Mama Chicken               1    North Indian
3     Chokho Jeeman Marwari Jain Bhojanalya               1      Rajasthani
4                            Pinch Of Spice               3    North Indian
...                                     ...             ...             ...
8638                               D Cabana               5     Continental
8639                               Kaloreez               3            Cafe
8640                                Plot 17               3          Burger
8641                       Vista - The Park               4        American
8642               Flying Spaghetti Monster               1         Italian

[8643 rows x 3 columns]

In [8]:
Average_muli_cuisines=df[df['Cuisines Count']>1]['Average Cost for two'].mean()
print(f"Average cost for Multi cuisine restaurants: {Average_muli_cuisines}")
Average_single_cuisine=df[df['Cuisines Count']==1]['Average Cost for two'].mean()
print(f"Average cost for two peoples in the restaurants that are serving single primary cuisine: {Average_single_cuisine}")

Average cost for Multi cuisine restaurants: 705.9058950784207
Average cost for two peoples in the restaurants that are serving single primary cuisine: 477.3062015503876

### Observation:
From the above result we can say that the average cost for two people are greater in Multi-Cuisine restaurants as compared to the cost for two people in a restaurant that serves only one cuisine.

In [9]:
df[['Restaurant Name', 'Votes']]

                            Restaurant Name  Votes
0                                Jahanpanah    140
1                       Rangrezz Restaurant     71
2                   Time2Eat - Mama Chicken     94
3     Chokho Jeeman Marwari Jain Bhojanalya     87
4                            Pinch Of Spice    177
...                                     ...    ...
8638                               D Cabana    193
8639                               Kaloreez     85
8640                                Plot 17    172
8641                       Vista - The Park     74
8642               Flying Spaghetti Monster    316

[8643 rows x 2 columns]

In [10]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Has Table booking', 'Has Online delivery',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'n_outlets', 'Is Chain', 'Is Rated', 'Is NCR',
       'Cuisines Count', 'Primary Cuisine'],
      dtype='object')

In [11]:
#Now we are converting the feature like has table booking and has Online Delivery to Binary flag like 0 and 1
df[['Restaurant Name', 'Has Table booking', 'Has Online delivery']]

,Restaurant Name,Has Table booking,Has Online delivery
0,Jahanpanah,No,No
1,Rangrezz Restaurant,No,No
2,Time2Eat - Mama Chicken,No,No
3,Chokho Jeeman Marwari Jain Bhojanalya,No,No
4,Pinch Of Spice,No,No
...,...,...,...
8638,D Cabana,No,No
8639,Kaloreez,No,No
8640,Plot 17,No,No
8641,Vista - The Park,No,No
8642,Flying Spaghetti Monster,No,No

In [12]:
df['Has Online delivery']=df['Has Online delivery'].map({
    'Yes': 1,
    'No':0
})
df['Has Table booking']=df['Has Table booking'].map({
    'Yes':1,
    'No':0
})

In [13]:
df[['Restaurant Name', 'Has Table booking', 'Has Online delivery']]

,Restaurant Name,Has Table booking,Has Online delivery
0,Jahanpanah,0,0
1,Rangrezz Restaurant,0,0
2,Time2Eat - Mama Chicken,0,0
3,Chokho Jeeman Marwari Jain Bhojanalya,0,0
4,Pinch Of Spice,0,0
...,...,...,...
8638,D Cabana,0,0
8639,Kaloreez,0,0
8640,Plot 17,0,0
8641,Vista - The Park,0,0
8642,Flying Spaghetti Monster,0,0

## Skewness:
It tell where the "extreme" values live:

- Positive skewnesss-Extreme values are on the right side

- Negetive skewness-Extreme values are on the left side

- Zero-This means data is balanced around the center

In [14]:
#checking the skewness of some of the columns:
votes_skewness=df['Votes'].skew()
print(votes_skewness)

9.651435215281888

### Observation:
We can see that the Votes are highly skew on the right side. Vast majority of the restaurants have very few votes. A tiny number of viral/popular restaurants have thousands of votes, creating massive right tail.

In [15]:
#Since the votes are heavily skewed on the right side applying the transformation on the votes column, this will make the charts, correlation and later models more reliable
df['Log_Votes']=np.log1p(df['Votes'])

In [16]:
os.makedirs('Output', exist_ok=True)
df.to_csv('Output/df_featured.csv', index=False)