# Feature Engineering on the cleaned Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv('Output/df_india_cleaned', encoding='latin-1')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,3400025,Jahanpanah,1,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",78.011544,27.161661,"North Indian, Mughlai",...,No,No,No,No,3,3.9,Yellow,Good,140,India
1,3400341,Rangrezz Restaurant,1,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",0.000000,0.000000,"North Indian, Mughlai",...,No,No,No,No,2,3.5,Yellow,Good,71,India
2,3400005,Time2Eat - Mama Chicken,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,North Indian,...,No,No,No,No,2,3.6,Yellow,Good,94,India
3,3400021,Chokho Jeeman Marwari Jain Bhojanalya,1,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,"Civil Lines, Agra",77.998092,27.195928,Rajasthani,...,No,No,No,No,2,4.0,Green,Very Good,87,India
4,3400017,Pinch Of Spice,1,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,"Civil Lines, Agra",78.007553,27.201725,"North Indian, Chinese, Mughlai",...,No,No,No,No,3,4.2,Green,Very Good,177,India

### Per-restaurant cuisines:
This are the number of cuisines that the restaurants servers.
### Primary cuisines:
This are the restaurant's main cuisine, zomato lists the dominant cuisines first.

In [7]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'Country'],
      dtype='object')

In [8]:
df['Cuisines']

0                                   North Indian, Mughlai
1                                   North Indian, Mughlai
2                                            North Indian
3                                              Rajasthani
4                          North Indian, Chinese, Mughlai
                              ...
6578    Continental, Seafood, Chinese, North Indian, B...
6579                          Cafe, North Indian, Chinese
6580                               Burger, Pizza, Biryani
6581            American, North Indian, Thai, Continental
6582                                              Italian
Name: Cuisines, Length: 6583, dtype: object

In [10]:
cuisines_split=df['Cuisines'].str.split(',')
df['Cuisines Count']=cuisines_split.apply(len)
df['Primary Cuisine']=cuisines_split.apply(lambda x: x[0])

In [11]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'Country', 'Cuisines Count', 'Primary Cuisine'],
      dtype='object')

In [12]:
df[['Restaurant Name', 'Cuisines Count', 'Primary Cuisine']]

                            Restaurant Name  Cuisines Count Primary Cuisine
0                                Jahanpanah               2    North Indian
1                       Rangrezz Restaurant               2    North Indian
2                   Time2Eat - Mama Chicken               1    North Indian
3     Chokho Jeeman Marwari Jain Bhojanalya               1      Rajasthani
4                            Pinch Of Spice               3    North Indian
...                                     ...             ...             ...
6578                               D Cabana               5     Continental
6579                               Kaloreez               3            Cafe
6580                                Plot 17               3          Burger
6581                       Vista - The Park               4        American
6582               Flying Spaghetti Monster               1         Italian

[6583 rows x 3 columns]

In [25]:
Average_muli_cuisines=df[df['Cuisines Count']>1]['Average Cost for two'].mean()
print(f"Average cost for Multi cuisine restaurants: {Average_muli_cuisines}")
Average_single_cuisine=df[df['Cuisines Count']==1]['Average Cost for two'].mean()
print(f"Average cost for two peoples in the restaurants that are serving single primary cuisine: {Average_single_cuisine}")

Average cost for Multi cuisine restaurants: 1.1425959528080831
Average cost for two peoples in the restaurants that are serving single primary cuisine: 0.7599995917646218

### Observation:
From the above result we can say that the average cost for two people are greater in Multi-Cuisine restaurants as compared to the cost for two people in a restaurant that serves only one cuisine.

In [26]:
df[['Restaurant Name', 'Votes']]

                            Restaurant Name  Votes
0                                Jahanpanah    140
1                       Rangrezz Restaurant     71
2                   Time2Eat - Mama Chicken     94
3     Chokho Jeeman Marwari Jain Bhojanalya     87
4                            Pinch Of Spice    177
...                                     ...    ...
6578                               D Cabana    193
6579                               Kaloreez     85
6580                                Plot 17    172
6581                       Vista - The Park     74
6582               Flying Spaghetti Monster    316

[6583 rows x 2 columns]

In [19]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'Country', 'Cuisines Count', 'Primary Cuisine'],
      dtype='object')